image: node:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules/

testing_testing:
  stage: test
  script: yarn test

deploy_to_ite:
  stage: deploy
  image: registry.gitlab.com/gitlab-examples/kubernetes-deploy
  script:
    - kubectl apply --validate=true  --filename=k8s_templates/user-deployment.yml
